// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteAdminBindByUuidData, DeleteAdminBindByUuidErrors, DeleteAdminBindByUuidResponses, DeleteServersByIdData, DeleteServersByIdErrors, DeleteServersByIdResponses, DeleteUploadsByIdData, DeleteUploadsByIdErrors, DeleteUploadsByIdResponses, GetAdminBoundPlayersData, GetAdminBoundPlayersResponses, GetAdminInfoData, GetAdminInfoErrors, GetAdminInfoResponses, GetAnalyticsOverviewData, GetAnalyticsOverviewResponses, GetAuthCheckData, GetAuthCheckResponses, GetHealthData, GetHealthResponses, GetServersByIdData, GetServersByIdErrors, GetServersByIdResponses, GetServersData, GetServersResponses, GetUploadsData, GetUploadsFileByAdminIdByFilenameData, GetUploadsFileByAdminIdByFilenameErrors, GetUploadsFileByAdminIdByFilenameResponses, GetUploadsResponses, PostAdminBindData, PostAdminBindErrors, PostAdminBindResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PostAuthLogoutData, PostAuthLogoutResponses, PostAuthRefreshData, PostAuthRefreshErrors, PostAuthRefreshResponses, PostAuthRegisterData, PostAuthRegisterErrors, PostAuthRegisterResponses, PostServersByIdStartData, PostServersByIdStartErrors, PostServersByIdStartResponses, PostServersByIdStopData, PostServersByIdStopErrors, PostServersByIdStopResponses, PostServersData, PostServersErrors, PostServersResponses, PostUploadsData, PostUploadsErrors, PostUploadsResponses, PutServersByIdData, PutServersByIdErrors, PutServersByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Bind a Minecraft player to admin account
 *
 * Associates a Minecraft player UUID with the authenticated admin
 */
export const postAdminBind = <ThrowOnError extends boolean = false>(options: Options<PostAdminBindData, ThrowOnError>): RequestResult<PostAdminBindResponses, PostAdminBindErrors, ThrowOnError> => (options.client ?? client).post<PostAdminBindResponses, PostAdminBindErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/bind',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Unbind a Minecraft player
 *
 * Removes the binding between the admin and a Minecraft player
 */
export const deleteAdminBindByUuid = <ThrowOnError extends boolean = false>(options: Options<DeleteAdminBindByUuidData, ThrowOnError>): RequestResult<DeleteAdminBindByUuidResponses, DeleteAdminBindByUuidErrors, ThrowOnError> => (options.client ?? client).delete<DeleteAdminBindByUuidResponses, DeleteAdminBindByUuidErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/bind/{uuid}',
    ...options
});

/**
 * Get all bound players
 *
 * Returns all Minecraft players bound to the authenticated admin
 */
export const getAdminBoundPlayers = <ThrowOnError extends boolean = false>(options?: Options<GetAdminBoundPlayersData, ThrowOnError>): RequestResult<GetAdminBoundPlayersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAdminBoundPlayersResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/bound-players',
    ...options
});

/**
 * Get admin profile
 *
 * Returns admin info including bound players
 */
export const getAdminInfo = <ThrowOnError extends boolean = false>(options?: Options<GetAdminInfoData, ThrowOnError>): RequestResult<GetAdminInfoResponses, GetAdminInfoErrors, ThrowOnError> => (options?.client ?? client).get<GetAdminInfoResponses, GetAdminInfoErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/info',
    ...options
});

/**
 * Get analytics overview
 *
 * Returns dashboard statistics for the authenticated admin
 */
export const getAnalyticsOverview = <ThrowOnError extends boolean = false>(options?: Options<GetAnalyticsOverviewData, ThrowOnError>): RequestResult<GetAnalyticsOverviewResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAnalyticsOverviewResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/analytics/overview',
    ...options
});

/**
 * Check if any admin is registered
 *
 * Returns whether at least one admin account exists in the system
 */
export const getAuthCheck = <ThrowOnError extends boolean = false>(options?: Options<GetAuthCheckData, ThrowOnError>): RequestResult<GetAuthCheckResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAuthCheckResponses, unknown, ThrowOnError>({ url: '/auth/check', ...options });

/**
 * Admin login
 *
 * Authenticates an admin with email and password, returns JWT tokens
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>): RequestResult<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError> => (options.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout admin
 *
 * Invalidates the refresh token, effectively logging out the admin
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(options: Options<PostAuthLogoutData, ThrowOnError>): RequestResult<PostAuthLogoutResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostAuthLogoutResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/auth/logout',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Refresh access token
 *
 * Exchanges a valid refresh token for a new access/refresh token pair
 */
export const postAuthRefresh = <ThrowOnError extends boolean = false>(options: Options<PostAuthRefreshData, ThrowOnError>): RequestResult<PostAuthRefreshResponses, PostAuthRefreshErrors, ThrowOnError> => (options.client ?? client).post<PostAuthRefreshResponses, PostAuthRefreshErrors, ThrowOnError>({
    url: '/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register a new admin account
 *
 * Creates a new admin account with email and password
 */
export const postAuthRegister = <ThrowOnError extends boolean = false>(options: Options<PostAuthRegisterData, ThrowOnError>): RequestResult<PostAuthRegisterResponses, PostAuthRegisterErrors, ThrowOnError> => (options.client ?? client).post<PostAuthRegisterResponses, PostAuthRegisterErrors, ThrowOnError>({
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health check
 *
 * Returns server health status and version
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * List all servers
 *
 * Returns all Minecraft servers belonging to the authenticated admin
 */
export const getServers = <ThrowOnError extends boolean = false>(options?: Options<GetServersData, ThrowOnError>): RequestResult<GetServersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetServersResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/servers',
    ...options
});

/**
 * Create a new server
 *
 * Adds a new Minecraft server entry for the authenticated admin
 */
export const postServers = <ThrowOnError extends boolean = false>(options: Options<PostServersData, ThrowOnError>): RequestResult<PostServersResponses, PostServersErrors, ThrowOnError> => (options.client ?? client).post<PostServersResponses, PostServersErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/servers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a server
 *
 * Removes a Minecraft server entry by ID
 */
export const deleteServersById = <ThrowOnError extends boolean = false>(options: Options<DeleteServersByIdData, ThrowOnError>): RequestResult<DeleteServersByIdResponses, DeleteServersByIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteServersByIdResponses, DeleteServersByIdErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/servers/{id}',
    ...options
});

/**
 * Get a single server
 *
 * Returns details of a specific Minecraft server by ID
 */
export const getServersById = <ThrowOnError extends boolean = false>(options: Options<GetServersByIdData, ThrowOnError>): RequestResult<GetServersByIdResponses, GetServersByIdErrors, ThrowOnError> => (options.client ?? client).get<GetServersByIdResponses, GetServersByIdErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/servers/{id}',
    ...options
});

/**
 * Update a server
 *
 * Updates an existing Minecraft server's details
 */
export const putServersById = <ThrowOnError extends boolean = false>(options: Options<PutServersByIdData, ThrowOnError>): RequestResult<PutServersByIdResponses, PutServersByIdErrors, ThrowOnError> => (options.client ?? client).put<PutServersByIdResponses, PutServersByIdErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/servers/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Start a server
 *
 * Sets a server's status to 'online'
 */
export const postServersByIdStart = <ThrowOnError extends boolean = false>(options: Options<PostServersByIdStartData, ThrowOnError>): RequestResult<PostServersByIdStartResponses, PostServersByIdStartErrors, ThrowOnError> => (options.client ?? client).post<PostServersByIdStartResponses, PostServersByIdStartErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/servers/{id}/start',
    ...options
});

/**
 * Stop a server
 *
 * Sets a server's status to 'offline'
 */
export const postServersByIdStop = <ThrowOnError extends boolean = false>(options: Options<PostServersByIdStopData, ThrowOnError>): RequestResult<PostServersByIdStopResponses, PostServersByIdStopErrors, ThrowOnError> => (options.client ?? client).post<PostServersByIdStopResponses, PostServersByIdStopErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/servers/{id}/stop',
    ...options
});

/**
 * List uploaded files
 *
 * Returns a list of files uploaded by the authenticated admin (latest 50)
 */
export const getUploads = <ThrowOnError extends boolean = false>(options?: Options<GetUploadsData, ThrowOnError>): RequestResult<GetUploadsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetUploadsResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/uploads',
    ...options
});

/**
 * Upload a file
 *
 * Uploads a file (image, zip, pdf, etc.) for the authenticated admin
 */
export const postUploads = <ThrowOnError extends boolean = false>(options: Options<PostUploadsData, ThrowOnError>): RequestResult<PostUploadsResponses, PostUploadsErrors, ThrowOnError> => (options.client ?? client).post<PostUploadsResponses, PostUploadsErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/uploads',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Serve/download an uploaded file
 *
 * Returns the raw file content with caching headers
 */
export const getUploadsFileByAdminIdByFilename = <ThrowOnError extends boolean = false>(options: Options<GetUploadsFileByAdminIdByFilenameData, ThrowOnError>): RequestResult<GetUploadsFileByAdminIdByFilenameResponses, GetUploadsFileByAdminIdByFilenameErrors, ThrowOnError> => (options.client ?? client).get<GetUploadsFileByAdminIdByFilenameResponses, GetUploadsFileByAdminIdByFilenameErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/uploads/file/{admin_id}/{filename}',
    ...options
});

/**
 * Delete an uploaded file
 *
 * Removes an upload record and its physical file from disk
 */
export const deleteUploadsById = <ThrowOnError extends boolean = false>(options: Options<DeleteUploadsByIdData, ThrowOnError>): RequestResult<DeleteUploadsByIdResponses, DeleteUploadsByIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteUploadsByIdResponses, DeleteUploadsByIdErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/uploads/{id}',
    ...options
});
