// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/api' | (string & {});
};

export type ModelsAdminInfo = {
    bound_players?: Array<string>;
    created_at?: string;
    email?: string;
    id?: string;
};

export type ModelsAnalyticsOverview = {
    bound_players?: number;
    daily_active?: number;
    online_rate?: number;
    online_servers?: number;
    storage_used?: number;
    total_players?: number;
    total_servers?: number;
    total_uploads?: number;
};

export type ModelsAuthResponse = {
    access_token?: string;
    admin?: ModelsAdminInfo;
    refresh_token?: string;
};

export type ModelsBindPlayerRequest = {
    player_name?: string;
    player_uuid: string;
};

export type ModelsBoundPlayer = {
    created_at?: string;
    player_name?: string;
    player_uuid?: string;
};

export type ModelsCreateServerRequest = {
    description?: string;
    host?: string;
    max_players?: number;
    name: string;
    port?: number;
    version?: string;
};

export type ModelsLoginRequest = {
    email: string;
    password: string;
};

export type ModelsMessageResponse = {
    message?: string;
};

export type ModelsRefreshRequest = {
    refresh_token: string;
};

export type ModelsRegisterRequest = {
    email: string;
    password: string;
};

export type ModelsServer = {
    admin_id?: string;
    created_at?: string;
    current_players?: number;
    description?: string;
    host?: string;
    id?: string;
    max_players?: number;
    name?: string;
    port?: number;
    status?: string;
    updated_at?: string;
    version?: string;
};

export type ModelsUpdateServerRequest = {
    description?: string;
    host?: string;
    max_players?: number;
    name?: string;
    port?: number;
    status?: string;
    version?: string;
};

export type ModelsUploadResponse = {
    content_type?: string;
    created_at?: string;
    file_size?: number;
    filename?: string;
    id?: string;
    original_name?: string;
    url?: string;
};

export type PostAdminBindData = {
    /**
     * Player UUID and optional name
     */
    body: ModelsBindPlayerRequest;
    path?: never;
    query?: never;
    url: '/admin/bind';
};

export type PostAdminBindErrors = {
    /**
     * player already bound
     */
    409: ModelsMessageResponse;
};

export type PostAdminBindError = PostAdminBindErrors[keyof PostAdminBindErrors];

export type PostAdminBindResponses = {
    /**
     * OK
     */
    200: ModelsMessageResponse;
};

export type PostAdminBindResponse = PostAdminBindResponses[keyof PostAdminBindResponses];

export type DeleteAdminBindByUuidData = {
    body?: never;
    path: {
        /**
         * Player UUID to unbind
         */
        uuid: string;
    };
    query?: never;
    url: '/admin/bind/{uuid}';
};

export type DeleteAdminBindByUuidErrors = {
    /**
     * binding not found
     */
    404: ModelsMessageResponse;
};

export type DeleteAdminBindByUuidError = DeleteAdminBindByUuidErrors[keyof DeleteAdminBindByUuidErrors];

export type DeleteAdminBindByUuidResponses = {
    /**
     * OK
     */
    200: ModelsMessageResponse;
};

export type DeleteAdminBindByUuidResponse = DeleteAdminBindByUuidResponses[keyof DeleteAdminBindByUuidResponses];

export type GetAdminBoundPlayersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/bound-players';
};

export type GetAdminBoundPlayersResponses = {
    /**
     * OK
     */
    200: Array<ModelsBoundPlayer>;
};

export type GetAdminBoundPlayersResponse = GetAdminBoundPlayersResponses[keyof GetAdminBoundPlayersResponses];

export type GetAdminInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/info';
};

export type GetAdminInfoErrors = {
    /**
     * Internal Server Error
     */
    500: ModelsMessageResponse;
};

export type GetAdminInfoError = GetAdminInfoErrors[keyof GetAdminInfoErrors];

export type GetAdminInfoResponses = {
    /**
     * OK
     */
    200: ModelsAdminInfo;
};

export type GetAdminInfoResponse = GetAdminInfoResponses[keyof GetAdminInfoResponses];

export type GetAnalyticsOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/analytics/overview';
};

export type GetAnalyticsOverviewResponses = {
    /**
     * OK
     */
    200: ModelsAnalyticsOverview;
};

export type GetAnalyticsOverviewResponse = GetAnalyticsOverviewResponses[keyof GetAnalyticsOverviewResponses];

export type GetAuthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/check';
};

export type GetAuthCheckResponses = {
    /**
     * registered status
     */
    200: {
        [key: string]: boolean;
    };
};

export type GetAuthCheckResponse = GetAuthCheckResponses[keyof GetAuthCheckResponses];

export type PostAuthLoginData = {
    /**
     * Login credentials
     */
    body: ModelsLoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * invalid email or password
     */
    401: ModelsMessageResponse;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: ModelsAuthResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthLogoutData = {
    /**
     * Refresh token to invalidate
     */
    body: ModelsRefreshRequest;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * OK
     */
    200: ModelsMessageResponse;
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type PostAuthRefreshData = {
    /**
     * Refresh token
     */
    body: ModelsRefreshRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * invalid or expired refresh token
     */
    401: ModelsMessageResponse;
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
    /**
     * OK
     */
    200: ModelsAuthResponse;
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthRegisterData = {
    /**
     * Registration info
     */
    body: ModelsRegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * invalid request body
     */
    400: ModelsMessageResponse;
    /**
     * email already registered
     */
    409: ModelsMessageResponse;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * Created
     */
    201: ModelsAuthResponse;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * status and version
     */
    200: {
        [key: string]: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetServersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/servers';
};

export type GetServersResponses = {
    /**
     * OK
     */
    200: Array<ModelsServer>;
};

export type GetServersResponse = GetServersResponses[keyof GetServersResponses];

export type PostServersData = {
    /**
     * Server details
     */
    body: ModelsCreateServerRequest;
    path?: never;
    query?: never;
    url: '/servers';
};

export type PostServersErrors = {
    /**
     * name is required
     */
    400: ModelsMessageResponse;
};

export type PostServersError = PostServersErrors[keyof PostServersErrors];

export type PostServersResponses = {
    /**
     * Created
     */
    201: ModelsServer;
};

export type PostServersResponse = PostServersResponses[keyof PostServersResponses];

export type DeleteServersByIdData = {
    body?: never;
    path: {
        /**
         * Server ID
         */
        id: string;
    };
    query?: never;
    url: '/servers/{id}';
};

export type DeleteServersByIdErrors = {
    /**
     * server not found
     */
    404: ModelsMessageResponse;
};

export type DeleteServersByIdError = DeleteServersByIdErrors[keyof DeleteServersByIdErrors];

export type DeleteServersByIdResponses = {
    /**
     * OK
     */
    200: ModelsMessageResponse;
};

export type DeleteServersByIdResponse = DeleteServersByIdResponses[keyof DeleteServersByIdResponses];

export type GetServersByIdData = {
    body?: never;
    path: {
        /**
         * Server ID
         */
        id: string;
    };
    query?: never;
    url: '/servers/{id}';
};

export type GetServersByIdErrors = {
    /**
     * server not found
     */
    404: ModelsMessageResponse;
};

export type GetServersByIdError = GetServersByIdErrors[keyof GetServersByIdErrors];

export type GetServersByIdResponses = {
    /**
     * OK
     */
    200: ModelsServer;
};

export type GetServersByIdResponse = GetServersByIdResponses[keyof GetServersByIdResponses];

export type PutServersByIdData = {
    /**
     * Fields to update
     */
    body: ModelsUpdateServerRequest;
    path: {
        /**
         * Server ID
         */
        id: string;
    };
    query?: never;
    url: '/servers/{id}';
};

export type PutServersByIdErrors = {
    /**
     * server not found
     */
    404: ModelsMessageResponse;
};

export type PutServersByIdError = PutServersByIdErrors[keyof PutServersByIdErrors];

export type PutServersByIdResponses = {
    /**
     * OK
     */
    200: ModelsServer;
};

export type PutServersByIdResponse = PutServersByIdResponses[keyof PutServersByIdResponses];

export type PostServersByIdStartData = {
    body?: never;
    path: {
        /**
         * Server ID
         */
        id: string;
    };
    query?: never;
    url: '/servers/{id}/start';
};

export type PostServersByIdStartErrors = {
    /**
     * server not found
     */
    404: ModelsMessageResponse;
};

export type PostServersByIdStartError = PostServersByIdStartErrors[keyof PostServersByIdStartErrors];

export type PostServersByIdStartResponses = {
    /**
     * OK
     */
    200: ModelsMessageResponse;
};

export type PostServersByIdStartResponse = PostServersByIdStartResponses[keyof PostServersByIdStartResponses];

export type PostServersByIdStopData = {
    body?: never;
    path: {
        /**
         * Server ID
         */
        id: string;
    };
    query?: never;
    url: '/servers/{id}/stop';
};

export type PostServersByIdStopErrors = {
    /**
     * server not found
     */
    404: ModelsMessageResponse;
};

export type PostServersByIdStopError = PostServersByIdStopErrors[keyof PostServersByIdStopErrors];

export type PostServersByIdStopResponses = {
    /**
     * OK
     */
    200: ModelsMessageResponse;
};

export type PostServersByIdStopResponse = PostServersByIdStopResponses[keyof PostServersByIdStopResponses];

export type GetUploadsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/uploads';
};

export type GetUploadsResponses = {
    /**
     * OK
     */
    200: Array<ModelsUploadResponse>;
};

export type GetUploadsResponse = GetUploadsResponses[keyof GetUploadsResponses];

export type PostUploadsData = {
    body: {
        /**
         * File to upload
         */
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/uploads';
};

export type PostUploadsErrors = {
    /**
     * invalid upload or file type not allowed
     */
    400: ModelsMessageResponse;
};

export type PostUploadsError = PostUploadsErrors[keyof PostUploadsErrors];

export type PostUploadsResponses = {
    /**
     * Created
     */
    201: ModelsUploadResponse;
};

export type PostUploadsResponse = PostUploadsResponses[keyof PostUploadsResponses];

export type GetUploadsFileByAdminIdByFilenameData = {
    body?: never;
    path: {
        /**
         * Admin ID
         */
        admin_id: string;
        /**
         * File path (including subdirs)
         */
        filename: string;
    };
    query?: never;
    url: '/uploads/file/{admin_id}/{filename}';
};

export type GetUploadsFileByAdminIdByFilenameErrors = {
    /**
     * access denied
     */
    403: ModelsMessageResponse;
};

export type GetUploadsFileByAdminIdByFilenameError = GetUploadsFileByAdminIdByFilenameErrors[keyof GetUploadsFileByAdminIdByFilenameErrors];

export type GetUploadsFileByAdminIdByFilenameResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteUploadsByIdData = {
    body?: never;
    path: {
        /**
         * Upload ID
         */
        id: string;
    };
    query?: never;
    url: '/uploads/{id}';
};

export type DeleteUploadsByIdErrors = {
    /**
     * upload not found
     */
    404: ModelsMessageResponse;
};

export type DeleteUploadsByIdError = DeleteUploadsByIdErrors[keyof DeleteUploadsByIdErrors];

export type DeleteUploadsByIdResponses = {
    /**
     * OK
     */
    200: ModelsMessageResponse;
};

export type DeleteUploadsByIdResponse = DeleteUploadsByIdResponses[keyof DeleteUploadsByIdResponses];
