// 统一导出所有页面组件
export { default as Home } from './Home';
export { default as AccountList } from './AccountList';
export { default as AccountListWithSidebar } from './AccountListWithSidebar';
export { default as InstanceManage } from './InstanceManage';
export { default as InstanceList } from './InstanceList';
export { default as Download } from './Download';
export { default as DownloadGame } from './DownloadGame';
export { default as DownloadModpack } from './DownloadModpack';
export { default as MicrosoftAccount } from './MicrosoftAccount';
export { default as OfflineAccount } from './OfflineAccount';
export { default as Settings } from './Settings';
export { default as Multiplayer } from './Multiplayer';
export { default as Feedback } from './Feedback';
export { default as Hint } from './Hint'
export { default as GameSettings } from './GameSettings';
export { default as GameSettingsJava } from './GameSettingsJava';
export { default as GameSettingsGeneral } from './GameSettingsGeneral';
export { default as GameSettingsAppearance } from './GameSettingsAppearance';
export { default as GameSettingsDownload } from './GameSettingsDownload';
