// 统一导出所有页面组件
export { default as Home } from './Home';
export { default as AccountList } from './AccountList/AccountList';
export { default as InstanceManage } from './Instance/InstanceManage';
export { default as InstanceList } from './Instance/InstanceList';
export { default as DownloadGame } from './Download/DownloadGame';
export { default as DownloadModpack } from './Download/DownloadModpack';
export { default as VersionDetailWithInstall } from './Download/VersionDetailWithInstall';
export { default as MicrosoftAccount } from './AccountList/MicrosoftAccount';
export { default as OfflineAccount } from './AccountList/OfflineAccount';
export { default as Settings } from './Settings';
export { default as Multiplayer } from './Multiplayer';
export { default as Feedback } from './Feedback/Feedback';
export { default as Hint } from './Feedback/Hint'
export { default as InstanceGameSettings } from './Instance/InstanceSettings/InstanceGameSettings';
export { default as InstanceAutoInstall } from './Instance/InstanceSettings/InstanceAutoInstall';
export { default as InstanceMods } from './Instance/InstanceSettings/InstanceMods';
export { default as InstanceResourcePacks } from './Instance/InstanceSettings/InstanceResourcePacks';
export { default as InstanceWorlds } from './Instance/InstanceSettings/InstanceWorlds';
export { default as VersionInstall } from './VersionInstall';
